stages:
  - unit test
  - deploy
  - integration test

Unit Tests:
  stage: unit test
  image: python:3.8
  only:
    - dev
  variables:
    MONGODB_URL: $MONGODB_URL_DEV
  script:
    - pip install -r requirements.txt
    - pycodestyle --max-line-length=95 .
    - pytest -v -m "not integration"

Deploy to Heroku DEV:
  stage: deploy
  image: ruby:latest
  only:
    - dev
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY

Deploy to Heroku PRD:
  stage: deploy
  image: ruby:latest
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRD --api-key=$HEROKU_API_KEY

Integration Tests:
  stage: integration test
  image: python:3.8
  script:
    - if [ $CI_COMMIT_REF_NAME = "master" ]; then MONGODB_URL=$MONGODB_URL_PRD; else MONGODB_URL=$MONGODB_URL_DEV; fi;
    - if [ $CI_COMMIT_REF_NAME = "master" ]; then HEROKU_APP=$HEROKU_APP_PRD; else HEROKU_APP=$HEROKU_APP_DEV; fi;
    - export MONGODB_URL
    - export HEROKU_APP
    - pip install -r requirements.txt
    - pytest -v -m integration
