stages:
  - Deploy to Heroku DEV
  - Deploy to Heroku PRD
  - Update Database DEV
  - Update Database PRD

Deploy to Heroku DEV:
  stage: Deploy to Heroku DEV
  image: ruby:latest
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'dev' &&
          $CI_PIPELINE_SOURCE != 'schedule' &&
          $CI_MERGE_REQUEST_ID"
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY

Deploy to Heroku PRD:
  stage: Deploy to Heroku PRD
  image: ruby:latest
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'master' && $CI_PIPELINE_SOURCE != 'schedule'"
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRD --api-key=$HEROKU_API_KEY
