stages:
  - test
  - deploy

Tests:
  stage: test
  image: python:3.8
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'dev'"
  script:
    - pip install -r requirements.txt
    - pycodestyle --max-line-length=95 app.py
    - pycodestyle --max-line-length=95 triggers.py
    - pycodestyle --max-line-length=95 backend/.
    - pytest -v

Deploy to Heroku DEV:
  stage: deploy
  image: ruby:latest
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'dev'"
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY

Deploy to Heroku PRD:
  stage: deploy
  image: ruby:latest
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'master'"
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRD --api-key=$HEROKU_API_KEY
